// <auto-generated />
namespace Wardship.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddCAFCASSInvolvedToWardshipRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCAFCASSInvolvedToWardshipRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "202407181343197_AddCAFCASSInvolvedToWardshipRecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
