name: Wardship-Modernisation-Platform

on:
  push:
    branches: [ "master", "working-commit", "staging" ]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
  IMAGE_TAG: ${{ github.sha }}
  ECS_SERVICE: ${{ vars.ECS_SERVICE }}
  ECS_CLUSTER: ${{ vars.ECS_CLUSTER }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}

permissions:
  contents: write

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/working-commit'
    name: Dev - Build & Deploy
    runs-on: windows-2019
    permissions:
      contents: write
      issues: write
      id-token: write
    environment: development

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework 4.6.1 Developer Pack
        run: |
          choco install netfx-4.6.1-devpack -y
        shell: powershell

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish
        run: |
          msbuild "Wardship.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}/WebApp.zip" /p:DeployIisAppPath="Default Web Site"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ github.workspace }}/WebApp.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t "wardship" .
          docker tag "wardship:latest" "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"
          docker push "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"

      - name: Force ECS Deployment
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment

  deploy-preprod:
    if: github.ref == 'refs/heads/staging'
    name: Preprod - Build & Deploy
    runs-on: windows-2019
    permissions:
      contents: write
      issues: write
      id-token: write
    environment: preproduction

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework 4.6.1 Developer Pack
        run: |
          choco install netfx-4.6.1-devpack -y
        shell: powershell

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish
        run: |
          msbuild "Wardship.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}/WebApp.zip" /p:DeployIisAppPath="Default Web Site"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ github.workspace }}/WebApp.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t "wardship" .
          docker tag "wardship:latest" "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"
          docker push "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"

      - name: Force ECS Deployment
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    name: Prod - Build & Deploy
    runs-on: windows-2019
    permissions:
      contents: write
      issues: write
      id-token: write
    environment: production

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework 4.6.1 Developer Pack
        run: |
          choco install netfx-4.6.1-devpack -y
        shell: powershell

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish
        run: |
          msbuild "Wardship.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="${{ github.workspace }}/WebApp.zip" /p:DeployIisAppPath="Default Web Site"

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ${{ github.workspace }}/WebApp.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/modernisation-platform-oidc-cicd
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and push it to ECR so that it can be deployed to ECS.
          docker build -t "wardship" .
          docker tag "wardship:latest" "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"
          docker push "${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest"

      - name: Force ECS Deployment
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
