CREATE TABLE [dbo].[WardshipRecords] (
    [WardshipCaseID]       INT            IDENTITY (1, 1) NOT NULL,
    [ChildSurname]         NVARCHAR (100) NULL,
    [ChildForenames]       NVARCHAR (100) NULL,
    [ChildDateofBirth]     DATETIME       NULL,
    [DateOfOS]             DATETIME       NULL,
    [FileNumber]           NVARCHAR (15)  NULL,
    [FileDuplicate]        NVARCHAR (10)  NULL,
    [Xreg]                 NVARCHAR (150) NULL,
    [TypeID]               INT            NULL,
    [CourtID]              INT            NULL,
    [StatusID]             INT            NULL,
    [GenderID]             INT            NULL,
    [RecordID]             INT            NULL,
    [LapsedID]             INT            NULL,
    [CWOID]                INT            NULL,
    [DistrictJudgeID]      INT            NULL,
    [CaseTypeID]           INT            NULL,
    [CAFCASSID]            INT            NULL,
    [LapseLetterSent]      DATETIME       NULL,
    [FirstAppointmentDate] DATETIME       NULL,
    [HearingDate]          DATETIME       NULL,
    [Username]             NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([WardshipCaseID] ASC),
    CONSTRAINT [WardshipRecord_CAFCASS] FOREIGN KEY ([CAFCASSID]) REFERENCES [dbo].[CAFCASSes] ([CAFCASSID]),
    CONSTRAINT [WardshipRecord_CaseType] FOREIGN KEY ([CaseTypeID]) REFERENCES [dbo].[CaseTypes] ([CaseTypeID]),
    CONSTRAINT [WardshipRecord_Court] FOREIGN KEY ([CourtID]) REFERENCES [dbo].[Courts] ([CourtID]),
    CONSTRAINT [WardshipRecord_CWO] FOREIGN KEY ([CWOID]) REFERENCES [dbo].[CWOes] ([CWOID]),
    CONSTRAINT [WardshipRecord_DistrictJudge] FOREIGN KEY ([DistrictJudgeID]) REFERENCES [dbo].[DistrictJudges] ([DistrictJudgeID]),
    CONSTRAINT [WardshipRecord_Gender] FOREIGN KEY ([GenderID]) REFERENCES [dbo].[Genders] ([GenderID]),
    CONSTRAINT [WardshipRecord_Lapsed] FOREIGN KEY ([LapsedID]) REFERENCES [dbo].[Lapseds] ([LapsedID]),
    CONSTRAINT [WardshipRecord_Record] FOREIGN KEY ([RecordID]) REFERENCES [dbo].[Records] ([RecordID]),
    CONSTRAINT [WardshipRecord_Status] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[Status] ([StatusID]),
    CONSTRAINT [WardshipRecord_Type] FOREIGN KEY ([TypeID]) REFERENCES [dbo].[Types] ([TypeID])
);

